config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  resources :event do
  resources :charges
  end
  resources :charges
  resources :event
  resources :user
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => "event#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  # after_create :welcome_send

  belongs_to :user
  belongs_to :event

  def welcome_send
    EventMailer.welcome_event(Event.find(event_id)).deliver_now
  end

end

app/models/event.rb
class Event < ApplicationRecord


  belongs_to :user
  has_many :attendances
  has_many :users, through: :attendances

  validate :event_must_be_in_the_future
  validates :start_date, presence: true
  validates :duration, presence: true, numericality: {only_integer: true},if: :is_multiple_of_5?
  validates :title, presence: true, length:  {in: 5..140}
  validates :description, presence: true, length: {in: 20..1000}
  validates :price, presence: true, inclusion: {in: 1..1000}
  validates :location, presence: true

  

  


  def is_multiple_of_5?
    duration % 5 == 0 ? true : false 
  end

  def event_must_be_in_the_future 
    errors.add(:start_date, "start date must be in the future") unless 
    start_date > Time.now 
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # after_create :welcome_send
  
  has_many :events
  has_many :attendances
  has_many :events, through: :attendances

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception

  def application 
    @user = User.find(params[:id])
  end
  
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  
  def index 
    @attendance = Attendance.where(event_id: params[:event_id])
    @event = Event.find(params[:event_id])
    
  end
  
  def new
    @event = Event.find(params[:event_id])
    @attendance = Attendance.new
    @amount = @event.price 
  end
  
  def create
    # Amount in cents
    @amount = Event.find(params[:event_id]).price
  
    customer = Stripe::Customer.create(
      :email => params[:stripeEmail],   
      :source  => params[:stripeToken]   
    )
  
    charge = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => @amount * 100,
      :description => 'Rails Stripe customer',
      :currency    => 'eur'
    )

    @attendance = Attendance.new(event_id: params[:event_id],
                                stripe_customer_id: customer.id,
                                user_id: current_user.id)
  
    # rescue Stripe::CardError => e
    # flash[:error] = e.message

    if @attendance.save
      redirect_to root_path 
    else
      puts attendance.errors.full_messages
      render 'new'
    end 
  end

  def show

  end
end

app/controllers/event_controller.rb
class EventController < ApplicationController

  before_action :authenticate_user!, except: [:index]
  # before_action :is_admin, only: [:edit, :destroy]

  def index
    @event = Event.all
  end

  def new
    @event = Event.new
  end

  def create 
    @event = Event.new(title: params[:title], 
                        description: params[:description], 
                        start_date: params[:start_date], 
                        duration: params[:duration], 
                        location: params[:location], 
                        price: params[:price],
                        user_id: current_user.id)
    if @event.save
      redirect_to '/'
    else
      puts @event.errors.full_messages
      render 'new'
    end
  end

  def show
    @event = Event.find(params[:id])
    @i = false
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    if  @event.update(title: params[:title], 
                      description: params[:description], 
                      start_date: params[:start_date], 
                      duration: params[:duration], 
                      location: params[:location], 
                      price: params[:price],
                      user_id: current_user.id)
      # flash[:info] = "Event successfully modified! "
      redirect_to event_path(@event.id)
    else 
      puts "@" * 60
      puts "@" * 60
      puts @event.errors.full_messages
      render 'edit'
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to root_path
  end

  def authenticate_admin
    current_user  == Event.find(params[:id]).user ? true : false
  end

end

app/controllers/user_controller.rb
class UserController < ApplicationController

  before_action :authenticate_user!
  before_action :only_see_your_own_page


  def show
    @user = User.find(params[:id])
    @event = Event.where(user_id: @user)
  end


  def only_see_your_own_page
    @user = User.find(params[:id])
    if current_user != @user
      redirect_to root_path, notice: "AHAH Bien essayé ! mais non…"
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  include UserHelper
  include EventHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/event_helper.rb
module EventHelper

  #  def is_admin
  #   current_user  == Event.find(params[:id]).user ? true : false
  # end

  # def is_user_but_not_admin
  #   current_user  != Event.find(params[:id]).user ? true : false
  # end
end

app/helpers/user_helper.rb
module UserHelper

  
end

app/views/charges/index.html.erb
<h1>La liste des invités : </h1>


</br>
<p><%= link_to 'Éditer l\'évènement', edit_event_path(@event.id), class: 'btn btn-outline-secondary' %></p>
</br>

<table class="table">
  <thead>
    <tr>
      <th scope="col">id</th>
      <th scope="col">Prénom</th>
      <th scope="col">Nom</th>
      <th scope="col">Email</th>
    </tr>
  </thead>
  <tbody>
<% @attendance.each do |f|  %>
    <tr> 
      <td><%= f.user_id %></td>
      
      <%# <td> f.first_name </td><td> f.last_name</td><td> f.email </td> %>
    </tr> 
<% end %>
</tbody>
</table>

app/views/charges/new.html.erb
<%= form_tag url_for(action: 'create'), method: "post" do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <h1>Redirection vers le formulaire de paiement</h1>
    <label class="amount">
      <span>Montant à payer: <%= @amount %>$</span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A month's subscription"
          data-currency="eur"
          data-amount="<%= @amount * 100 %>"
          data-locale="auto"></script>
<% end %>

app/views/event/edit.html.erb
<h1>Editer l'évènement:</h1>

<% if current_user == @event.user %>
<p>Envie d'annuler l'évènement ? <a href="<%= event_path(@event.id)%>" class="btn btn-danger" data-confirm="êtes vous sur ?" data-method="DELETE" >Supprimer</a></p>
<% end%>

<%= form_tag url_for(action: 'update'), method: "patch" do %>
<div class="form-group">
<%= label_tag 'titre' %>
<%= text_field_tag 'title', @event.title, class: 'form-control'%>
</div>
<div class="form-group">
<%= label_tag 'description' %>
<%= text_area_tag 'description', @event.description, class: 'form-control' %>
</div>
<div class="form-group">
<%= label_tag 'date' %>
<%= date_field_tag 'start_date', @event.start_date, class: 'form-control' %>
</div>
<div class="form-group">
<%= label_tag 'durée' %>
<%= number_field_tag 'duration', @event.duration, class: 'form-control' %>
</div>
<div class="form-group">
<%= label_tag 'lieu' %>
<%= text_field_tag 'location', @event.location, class: 'form-control' %>
</div>
<div class="form-group">
<%= label_tag 'prix' %>
<%= number_field_tag 'price', @event.price, class: 'form-control' %>
</div>
<div class="form-group">
<button type="submit" class="btn btn-primary">Envoyer</button>
</div>
<% end %>

app/views/event/index.html.erb
<h1>Liste des évènements: </h1>
</br>
<p>Envie de créer un évènment ?  <%=link_to ' Par ici ', new_event_path, class: 'btn btn-outline-secondary'%></p>
</br>
<table class="table">
  <thead>
    <tr>
      <%# <th scope="col">Titre</th> %>
      <th scope="col">Titre</th>
      <th scope="col">Date</th>
      <th scope="col">Durée</th>
      <th scope="col">Lieu</th>
      <th scope="col">Prix</th>
      <th scope="col"> </th>
    </tr>
  </thead>
  <tbody>
  <% @event.each do |f|%>
    <tr>
      
      <td><%= f.title %></td><td><%= f.start_date.strftime("%Y-%m-%d") %></td><td><%= f.duration %> min</td><td><%= f.location %></td><td><%= f.price %>$</td><td><%= link_to 'en savoir plus', event_path(f.id), class: 'btn btn-outline-secondary' %></td> 
    </tr>
    <% end%>
  </tbody>
</table>

app/views/event/new.html.erb
<h1>Nouvel evenement</h1>
</br>

<%= form_tag url_for(action: 'create'), method: "post" do %>
<div class="form-group">
<%= label_tag 'titre' %>
<%= text_field_tag 'title', @event.title, class: 'form-control'%>
</div>
<div class="form-group">
<%= label_tag 'description' %>
<%= text_area_tag 'description', @event.description, class: 'form-control' %>
</div>
<div class="form-group">
<%= label_tag 'date' %>
<%= date_field_tag 'start_date', @event.start_date, class: 'form-control' %>
</div>
<div class="form-group">
<%= label_tag 'durée' %>
<%= number_field_tag 'duration', @event.duration, class: 'form-control' %>
</div>
<div class="form-group">
<%= label_tag 'lieu' %>
<%= text_field_tag 'location', @event.location, class: 'form-control' %>
</div>
<div class="form-group">
<%= label_tag 'prix' %>
<%= number_field_tag 'price', @event.price, class: 'form-control' %>
</div>
<div class="form-group">
<button type="submit" class="btn btn-primary">Envoyer</button>
</div>
<% end %>

 

app/views/event/show.html.erb
<h1>page de l'évènement <%= @event.title %></h1>



<p><%= @event.title %></p>
<p><%= @event.description %></p>
<p><%= @event.start_date %></p>
<p><%= @event.duration %></p>
<p><%= @event.location %></p>
<p><%= @event.price %></p>

<% if current_user != @event.user  %>
  <%= link_to 'rejoindre l\'évènement', new_event_charge_path(@event.id), class: 'btn btn-outline-secondary' %>
<%end%>

<% if current_user == @event.user %>
  <%= link_to 'Mon espace', event_charges_path(@event.id), class: 'btn btn-outline-secondary' %>
<% end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EventbriteThp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.0/js/bootstrap.min.js" integrity="sha384-7aThvCh9TypR7fIc2HV4O/nFMVCBwyIUKL8XCtKE+8xgCgl/PQGuFsvShjr74PBp" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.0/css/bootstrap.min.css" integrity="sha384-PDle/QlgIONtM1aqA2Qemk5gPOE7wFq8+Em+G/hmo5Iq0CCmYZLv3fVRDJ4MMwEA" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <%# ============= NAVBAR ==================== %>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand ml-5" href="#">Eventbrite</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto mr-5">
      <li class="nav-item active">
        <a class="nav-link" href="/">Accueil</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= new_event_path %>">Evenement</a>
      </li>
      <% if user_signed_in? %>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Espace perso
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <span class="dropdown-item"><%= link_to "Se deconnecter", destroy_user_session_path, method: :delete %></span>       
          <span class="dropdown-item"><%= link_to "Mon profil", user_path(current_user.id) %></span>
        </div>
        <% else %>
        <li class="nav-item">
        <a class="nav-link" href="<%= new_user_session_path %>">Se connecter</a>
      </li>
        <% end%>
      </li>
    </ul>
  </div>
</nav>
</br>


   <%# ============= BODY ==================== %>

  <div class="container">
    <%= yield %>
  </div>

   <%# ============= FOOTER ==================== %>

  </body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
  <head>
  <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.0/js/bootstrap.min.js" integrity="sha384-7aThvCh9TypR7fIc2HV4O/nFMVCBwyIUKL8XCtKE+8xgCgl/PQGuFsvShjr74PBp" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.0/css/bootstrap.min.css" integrity="sha384-PDle/QlgIONtM1aqA2Qemk5gPOE7wFq8+Em+G/hmo5Iq0CCmYZLv3fVRDJ4MMwEA" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>

  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand ml-5" href="#">Eventbrite</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto mr-5">
      <li class="nav-item active">
        <a class="nav-link" href="/">Accueil</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= new_event_path %>">Evenement</a>
      </li>
      <% if user_signed_in? %>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Espace perso
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <span class="dropdown-item"><%= link_to "Se deconnecter", destroy_user_session_path, method: :delete %></span>       
          <span class="dropdown-item"><%= link_to "Mon profil", user_path(current_user.id) %></span>
        </div>
        <% else %>
        <li class="nav-item">
        <a class="nav-link" href="<%= new_user_session_path %>">Se connecter</a>
      </li>
        <% end%>
      </li>
    </ul>
  </div>
</nav>
</br>
<div class=container>
    <%= yield %>
    </div>
  </body>
</html>

app/views/user/show.html.erb
<h1>Bienvenue <%= @user.first_name %></h1>

<h3>Voici la liste de tes évènements : </h3>
</br>
<p>Pour éditer votre <%= link_to 'par ici', edit_user_registration_path %></p>
<div class="row">
    <%@event.all.each do |e| %>
      <div class="col-sm-3 mb-4">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title text-center"><%= e.title %></h5>
            <p class="card-text text-center"><%= e.description%></p>
            <%# <a href="#" class="btn btn-primary">Go somewhere</a> %>
          </div>
        </div>
      </div>
    <% end%>
  </div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>